---
- name: Load stored resource groups
  include_vars:
    file: vars/resource_group.yml
    name: master_resources

- name: Get facts for all resource groups
  azure.azcollection.azure_rm_resourcegroup_info:
  register: resourcegroups
  
- name: Gather resource group names
  set_fact:
    resourcegroupnames: "{{ resourcegroupnames }} + [ '{{ item.name }}' ]"
  loop: "{{ resourcegroups.resourcegroups }}"

- name: Print difference resources
  debug:
    msg: "{{ resourcegroupnames | difference(master_resources.resource_group) }}"

- name: Set facts to remove the extra resource groups
  set_fact:
    resource_group_names: "{{ resourcegroupnames | difference(master_resources.resource_group) }}"
