---
- name: Create Azure Report
  hosts: localhost
  tasks:

    - name: Gather Azure info
      ansible.builtin.include_role:
        name: azure_gather_info

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_cloud
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
