---
- name: Create Azure Detailed Report
  hosts: localhost
  tasks:

    - name: Gather Azure Detailed info
      ansible.builtin.include_role:
        name: azure_retrieve_info

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_azure
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
