- name: Gather Function App
  hosts: localhost
  gather_facts: false

  vars:
    functionappnames: []

  collections:
    - azure.azcollection

  tasks: 

    - name: Get facts for all function apps
      azure.azcollection.azure_rm_functionapp_info:
        resource_group: Demo
      register: functionapp
      
    - name: Gather functionapp group names
      set_fact:
        functionappnames: "{{ functionappnames }} + [ '{{ item.name }}' ]"
      loop: "{{ functionapp.ansible_info.azure_functionapps }}"
      when: functionapp != []

    - name: Sync with Gitrepo      
      git:
        repo: 'git@github.com:shadowman-lab/Ansible-Demo-Customer.git'
        dest: /home/git
      delegate_to: tower.shadowman.dev

    - name: Save Master function apps Groups
      copy:
        content: "function_app: {{ functionappnames }}"
        dest: "/home/git/vars/functionapp.yml"
      delegate_to: tower.shadowman.dev

    - name: Update git repo with new master function app
      shell: git add * && git commit -m "Adding new master function app to repo" && git push ||  /bin/true
      args:
        chdir: /home/git
      delegate_to: tower.shadowman.dev
      register: result
      changed_when: '"Adding new master function app to repo" in result.stdout'

    
      


      
