- name: Compare FunctionApp
  hosts: localhost
  gather_facts: false

  tasks: 

    - name: Functionapp compare
      include_role: 
        name: azure_compare_function_app

    - name: Remove extra functionapp
      include_role: 
        name: azure_remove_fuction_app
      when: functionapp_names != []
