---
- name: Compare inventories
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Inventory compare
      include_role:
        name: azure_compare_vm

    - name: Remove extra hosts
      include_role:
        name: azure_remove_vm
      when: vm_names != []
