- name: Compare Storage Account
  hosts: localhost
  gather_facts: false

  tasks: 

    - name: Storage Account compare
      include_role: 
        name: azure_compare_storage_account
        
    - name: Remove extra storage
      include_role: 
        name: azure_remove_storage_account
      when: storage_account_names != []
