---
- name: Load stored functionapp
  ansible.builtin.include_vars:
    file: vars/functionapp.yml
    name: master_functionapp

- name: Get facts for all function apps
  azure.azcollection.azure_rm_functionapp_info:
    resource_group: Demo
  register: functionapp

- name: Gather functionapp group names
  ansible.builtin.set_fact:
    functionappnames: "{{ functionappnames }} + [ '{{ item.name }}' ]"
  loop: "{{ functionapp.ansible_info.azure_functionapps }}"
  when: functionapp != []

- name: Print difference functionapp
  ansible.builtin.debug:
    msg: "{{ functionappnames | difference(master_functionapp.function_app) }}"

- name: Set facts to remove the extra functionapp
  ansible.builtin.set_fact:
    functionapp_names: "{{ functionappnames | difference(master_functionapp.function_app) }}"
