---
- name: Get facts for one Public IP
  azure_rm_publicipaddress_info:
    resource_group: "{{ resource_group_name }}"
    name: "{{ item }}01"
  register: publicipaddresses
  when: publisher == "MicrosoftWindowsServer"

- name: set public ip address fact
  set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"
  when: publisher == "MicrosoftWindowsServer"

- name: wait for the WinRM port to come online
  wait_for:
    port: 5986
    host: '{{ publicipaddress }}'
    timeout: 600
  when: publisher == "MicrosoftWindowsServer"