---
- name: Change facts if running Windows
  ansible.builtin.set_fact:
    sku: 'servercore-2016'
    version: '0.0.1'
    publisher: "cloud-infrastructure-services"
    offer: "servercore-2016"
  when: operating_system is match("Win.*")

- name: Change facts if running RHEL8
  ansible.builtin.set_fact:
    sku: 'rhel-lvm84'
    version: '8.4.2021053101'
  when: operating_system == "RHEL8"

- name: Provision instance
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{ item }}"
    storage_account: "{{ storage_account_name }}"
    admin_username: "{{ azureuser }}"
    admin_password: "{{ azurepassword }}"
    vm_size: "{{ vm_size }}"
    image:
      publisher: "{{ publisher }}"
      offer: "{{ offer }}"
      version: "{{ version }}"
      sku: "{{ sku }}"
  loop: "{{ vm_names }}"