---
- name: Change facts if running Windows
  ansible.builtin.set_fact:
    sku: 'servercore-2016'
    publisher: "cloud-infrastructure-services"
    offer: "servercore-2016"
  when: operating_system is match("Win.*")

- name: Change facts if running RHEL8
  ansible.builtin.set_fact:
    sku: 'rhel-lvm84'
    plan_name: "Red Hat Enterprise Linux 8.4 (BYOS)"
  when: operating_system == "RHEL8"

- name: Provision instance
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{ item }}"
    storage_account: "{{ storage_account_name }}"
    admin_username: "{{ azureuser }}"
    admin_password: "{{ azurepassword }}"
    vm_size: "{{ vm_size }}"
    open_ports:
      - 22
      - 80
      - 443
      - 5985
    accept_terms: yes
    image:
      publisher: "{{ publisher }}"
      offer: "{{ offer }}"
      version: "{{ version }}"
      sku: "{{ sku }}"
    plan:
      name: "{{ sku }}"
      product: "{{ offer }}"
      publisher: "{{ publisher }}"
  loop: "{{ vm_names }}"