---
- name: Change facts if running Windows
  ansible.builtin.set_fact:
    sku: 'windows2016'
    version: '20.01.10'
    publisher: "microsoft-ads"
    offer: "windows-data-science-vm"
    admin_user: "{{ windowsuser }}"
    admin_password: "{{ windowspassword }}"
  when: operating_system is match("Win.*")

- name: Change facts if running RHEL8
  ansible.builtin.set_fact:
    sku: '8.2'
    version: '8.2.2021040911'
  when: operating_system == "RHEL8"

- name: Provision instance
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{ item }}"
    storage_account: "{{ storage_account_name }}"
    admin_username: "{{ admin_user }}"
    admin_password: "{{ admin_password }}"
    vm_size: "{{ vm_size }}"
    image:
      publisher: "{{ publisher }}"
      offer: "{{ offer }}"
      version: "{{ version }}"
      sku: "{{ sku }}"
  loop: "{{ vm_names }}"