---
- name: Create Parking Exempt Status Job with Hosts
  ansible.controller.job_template:
    name: kcolby - Cloud Parking - Set Parking Exempt Status New
    job_type: run
    inventory: Azure Inventory
    project: kcolby - automate-infrastructure-optimization
    playbook: set_parkingexempt.yml
    credentials:
      - Azure Playbook Credentials
      - Cloud_Parking
    survey_enabled: true
    concurrent_jobs_enabled: true
    survey_spec: "{{ lookup('template', 'templates/hosts.j2') }}"
    validate_certs: false
    controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
  delegate_to: localhost
  run_once: true
