---
- name: Create Restore Job Template
  ansible.controller.job_template:
    name: "A Test"
    job_type: "run"
    inventory: "Network Inventory"
    project: "SSP Networking Project"
    playbook: "network_restore.yml"
    credentials: 
      - "Cisco Credentials" 
      - "VYOS Credentials"
      - "Arista Credential"
    limit: "os_cisco"
    survey_enabled: true
    become_enabled: yes
    survey_spec: "{{ lookup('template', 'templates/backup.j2') }}"
    validate_certs: no
    controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
  delegate_to: localhost
  run_once: true