---
- name: Get Azure VM Info
  azure.azcollection.azure_rm_virtualmachine_info:
    tags:
      - owner
  register: azurevms

- name: debug
  ansible.builtin.debug:
    msg: "{{ item.name }} {{ item.tags.owner }}"
  loop: "{{ azurevms.vms }}"
