---
- name: Get Azure VM Info
  azure.azcollection.azure_rm_virtualmachine_info:
  register: instance_info

- name: Set the un-tagged and missing owner to vars
  ansible.builtin.set_fact:
    untagged_instances: "{{ instance_info.vms | selectattr('tags', 'equalto', {}) | map(attribute='name') | list }}"
    missing_owner: "{{ instance_info.vms | selectattr('tags.owner', 'undefined') | map(attribute='name') | list }}"

- name: Display un-tagged instances
  ansible.builtin.debug:
    msg: "{{ untagged_instances }}"

- name: Terminate every un-tagged instance
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ hostvars[item].resource_group }}"
    state: absent
  loop: "{{ untagged_instances }}"
  when: untagged_instances | length  > 0

- name: Display instances missing owner
  ansible.builtin.debug:
    msg: "{{ missing_owner }}"

- name: Stop every non owner instance
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ hostvars[item].resource_group }}"
    started: false
  loop: "{{ missing_owner }}"
  when: missing_owner | length  > 0
