---
- name: Image facts
  azure.azcollection.azure_rm_virtualmachineimage_info:
    location: "{{ location }}"
    publisher: "{{ publisher | default(omit) }}"
    offer: "{{ offer | default(omit) }}"
    sku: "{{ sku | default(omit) }}"
