---
galaxy_info:
  author: Alex Dworjan
  description: Build Cloud Report
  company: Red Hat, Inc.
  license: Apache License 2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
  galaxy_tags:
    - system
